services: 
  virt-manager:
    image: docker-virt-manager:latest
    restart: always
    ports:
      - 8185:80
    environment:
    # Substitute comma separated qemu connect strings, e.g.: 
    # HOSTS: "['qemu+ssh://user@host1/system', 'qemu+ssh://user@host2/system']"
      HOSTS: "[]"
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro 
